[package]
name = "cl_signatures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = "0.4.2"
ark-secp256k1 = "0.4.0"
ark-std = "0.4.0"
rand = "0.8.5"
sha2 = "0.10.8"
