[package]
name = "zkp"
version = "0.1.0"
edition = "2021"

[dependencies]
mcore={path="mcore", version="0.1.0",features = ["std"]}
rand_core = { version = "0.5", features = ["std"] }
rand = "0.4"
sha2="0.9.8"

[features]
std = []